### ISSUE TITLE
Oneplus One Camera flash

### ISSUE THREAD

**Issue by rocky58** [ubports/camera-app#47] opened 2017-12-12 09:23 UTC
Hi all,
I have the problem that my Oneplus One camera flash doesn't work. With android it was working.

Any idea?

**Comment by dark-eye** [comment] 2017-12-12 10:02
Hey @rocky58,

Is it only when using the photo mode  or both in video and photo modes?

**Comment by rocky58** [comment] 2017-12-12 10:11
I tried only in photo mode

Il 12 dic 2017 11:02, "Eran" <notifications@github.com> ha scritto:

Hey @rocky58 <https://github.com/rocky58>,

Is it only when using the photo mode or both in video and photo modes?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ubports/camera-app/issues/47#issuecomment-351003501>,
or mute the thread

**Comment by NeoTheThird** [comment] 2017-12-12 10:33
To confirm it's not a hardware problem, could you try opening the battery indicator (swipe down from the battery in the top bar) and activating the flashlight there? If that works, this is most likely a duplicate of https://github.com/ubports/ubuntu-touch/issues/258.

**Comment by rocky58** [comment] 2017-12-12 12:37
Yes. It works...

Rocco Foti

Il 12 Dic 2017 11:33, "Jan Sprinz" <notifications@github.com> ha scritto:

**Comment by NeoTheThird** [comment] 2017-12-12 12:43
Ok, thanks.

**Closed by NeoTheThird** 2017-12-12 12:43 UTC

**Comment by rocky58** [comment] 2017-12-12 14:01
Without solution, so?

Il 12 dic 2017 13:43, "Jan Sprinz" <notifications@github.com> ha scritto:

**Comment by NeoTheThird** [comment] 2017-12-12 14:21
As I said, it's already been reported at https://github.com/ubports/ubuntu-touch/issues/258.

**Comment by rocky58** [comment] 2017-12-12 14:27
OK. Thanks

Il 12 dic 2017 15:21, "Jan Sprinz" <notifications@github.com> ha scritto:
