### ISSUE TITLE
No photo taken by pressing the dedicated physical button

### ISSUE THREAD

**Issue by Anne017** [ubports/camera-app#57] opened 2018-02-28 09:54 UTC
Device: FP2
Channel: stable
Build: 15.04 r3 (OTA 3)

Steps to reproduce: open the camera app, press the dedicated physical button (on the Fairphone 2, it is located at the right of the phone, below the power button).

Expected behavior: photo saved (same behavior than pressing the camera icon on the screen).

Actual behavior: nothing happens.

**Comment by Anne017** [comment] 2018-02-28 09:59
![capture](https://user-images.githubusercontent.com/17686836/36781559-7a4e78d8-1c76-11e8-9517-31088b9a2ff7.png)

**Comment by Anne017** [comment] 2018-02-28 10:00
See also Add buttons #16

**Comment by NeoTheThird** [comment] 2018-02-28 10:09
Support for this button needs to be implemented on a lower level, so this is a duplicate of https://github.com/ubports/ubuntu-touch/issues/33. Thanks for reporting, though :)

**Closed by NeoTheThird** 2018-02-28 10:09 UTC
